# 🎯 Notebook 04: Indexing and Selection

Time to slice and dice.

In this notebook, you'll:
- Use `.loc[]` for label-based selection
- Use `.iloc[]` for position-based selection
- Create boolean masks to filter rows
- Select specific columns and rows (solo or together)

Let the chaos of index manipulation begin.
---

In [1]:
import pandas as pd
import seaborn as sns

# We'll use the Titanic dataset again
df = sns.load_dataset("titanic")
df.head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

## 🔎 Select rows by label with `.loc[]`

In [2]:
# .loc[row_label, column_label]
# Titanic uses default RangeIndex, so labels are integers
print(df.loc[0])

# Row range (inclusive!)
df.loc[0:4, ["age", "fare", "sex"]]

survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object

    age     fare     sex
0  22.0   7.2500    male
1  38.0  71.2833  female
2  26.0   7.9250  female
3  35.0  53.1000  female
4  35.0   8.0500    male

## 🔢 Select rows by position with `.iloc[]`

In [3]:
# iloc uses pure positions
df.iloc[0]  # First row

# Row slice, column slice
df.iloc[1:4, 0:5]

   survived  pclass     sex   age  sibsp
1         1       1  female  38.0      1
2         1       3  female  26.0      0
3         1       1  female  35.0      1

## 🎯 Boolean Masking (Filtering)

In [4]:
# Filter passengers under age 10
kids = df[df["age"] < 10]
kids[["age", "sex", "class"]].head()

    age     sex   class
7   2.0    male   Third
10  4.0  female   Third
16  2.0    male   Third
24  8.0  female   Third
43  3.0  female  Second

## 🧠 Compound Conditions

In [5]:
# Adults in First Class who paid over $100
rich_folks = df[(df["age"] > 18) & (df["class"] == "First") & (df["fare"] > 100)]
rich_folks[["age", "class", "fare"]].head()

      age  class      fare
27   19.0  First  263.0000
88   23.0  First  263.0000
118  24.0  First  247.5208
195  58.0  First  146.5208
215  31.0  First  113.2750

## 🧹 Select Columns Only

In [6]:
df[["sex", "age", "embarked"]].head()

      sex   age embarked
0    male  22.0        S
1  female  38.0        C
2  female  26.0        S
3  female  35.0        S
4    male  35.0        S

## 🎯 Your Turn

1. Select the first row using `.iloc[]`, then again using `.loc[]`.
2. Slice the first 5 rows and select only `survived`, `sex`, and `age` columns.
3. Filter the dataset for female passengers over 40.
4. Create a DataFrame of passengers in 2nd class under age 15.
5. Use `.loc[]` to select the rows 10–20 and only the columns `fare`, `class`, and `age`.

🎯 **Bonus:** Find passengers with missing `age` and print only their `name`, `age`, and `pclass` (use `.isnull()`).

In [8]:
print("First row (iloc):\n", df.iloc[0])
print("First row (loc):\n", df.loc[0])


subset = df.loc[0:4, ["survived", "sex", "age"]]
print("\nSubset:\n", subset)

females_over_40 = df[(df["sex"] == "female") & (df["age"] > 40)]
print(f"\nFemales over 40 count: {len(females_over_40)}")

young_2nd_class = df[(df["pclass"] == 2) & (df["age"] < 15)]
print("\nYoung 2nd Class:\n", young_2nd_class.head())

print("\nRows 10-20 specific cols:\n", df.loc[10:20, ["fare", "pclass", "age"]])

First row (iloc):
 survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object
First row (loc):
 survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object

Subset:
    survived     sex   age
0         0    male  22.0
1         1  female  38.0
2         1  female  26.0
3         1  female  35.0
4         0    male  35.0

Females over 40 count: 48

Young 2nd Class:
      survived  pclass     sex    age  sibsp  parch     fare embarked   class  \
9           1       2  female  14.00      1      0  30.0708        C  Second
43          1       2  female   3.00      1      2  41.5792        C  Second
58          1       2  female   5.00      1      2  27.7500        S  Second
78          1       2    male   0.83      0      2  29.0000        S  Second
183         1       2    male   1.00      2      1  39.0000        S  Second

       who  adult_male deck  embark_town alive  alone
9    child       False  NaN    Cherbourg   yes  False
43   child       False  NaN    Cherbourg   yes  False
58   child       False  NaN  Southampton   yes  False
78   child       False  NaN  Southampton   yes  False
183  child       False    F  Southampton   yes  False

Rows 10-20 specific cols:
        fare  pclass   age
10  16.7000       3   4.0
11  26.5500       1  58.0
12   8.0500       3  20.0
13  31.2750       3  39.0
14   7.8542       3  14.0
15  16.0000       2  55.0
16  29.1250       3   2.0
17  13.0000       2   NaN
18  18.0000       3  31.0
19   7.2250       3   NaN
20  26.0000       2  35.0

---
## 🧼 Why This Matters

Being able to surgically select parts of your dataset is the core of real analysis. Whether you're cleaning junk or feeding a model, proper indexing = power.

Next: cleaning your data with `.dropna()`, `.fillna()`, and more. The fun begins when you try to fix the stuff that's broken.