# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date  None
2  Charlie      35     2022/03/01  88.0
3    David     NaN           None  92.5
4     None      40  April 5, 2022

### 🧯 2. Detecting Missing or Broken Values

In [2]:
df.isnull()

    Name    Age  Signup Date  Score
0  False  False        False  False
1  False  False        False   True
2  False  False        False  False
3  False   True         True  False
4   True  False        False  False

In [3]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
dtype: int64

In [4]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score
1    Bob  thirty     not a date  None
3  David     NaN           None  92.5
4   None      40  April 5, 2022

### 🧹 3. Cleaning Strategy Options

In [5]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0
})

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date   0.0
2  Charlie      35     2022/03/01  88.0
3    David      -1     1970-01-01  92.5
4  Unknown      40  April 5, 2022

In [6]:
df.dropna()

      Name Age Signup Date Score
0    Alice  25  2022-01-01  95.5
2  Charlie  35  2022/03/01  88.0

### 🧬 4. Data Type Fixes

In [7]:
df.dtypes

Name           object
Age            object
Signup Date    object
Score          object
dtype: object

In [8]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                   object
Age                   float64
Signup Date    datetime64[ns]
Score                 float64
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [9]:
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)

In [10]:
df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

In [11]:
df["Name"].fillna("Unknown", inplace=True)

### 🤓 6. Cleaned Data Review

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      object
 1   Age          5 non-null      float64
 2   Signup Date  5 non-null      datetime64[ns]
 3   Score        5 non-null      float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 292.0+ bytes

In [13]:
df.describe(include="all")

         Name        Age          Signup Date     Score
count       5   5.000000                    5   5.00000
unique      5        NaN                  NaN       NaN
top     Alice        NaN                  NaN       NaN
freq        1        NaN                  NaN       NaN
mean      NaN  34.000000  2022-01-01 00:00:00  92.00000
min       NaN  25.000000  2022-01-01 00:00:00  88.00000
25%       NaN  35.000000  2022-01-01 00:00:00  92.00000
50%       NaN  35.000000  2022-01-01 00:00:00  92.00000
75%       NaN  35.000000  2022-01-01 00:00:00  92.50000
max       NaN  40.000000  2022-01-01 00:00:00  95.50000
std       NaN   5.477226                  NaN   2.66927

### 🧪 Try It Yourself

Modify the `data` dictionary at the top of this notebook. Add:
- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly
Then re-run the notebook and fix it step-by-step.

In [23]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None, "Frank"],
    "Age": ["25", "thirty", 35, np.nan, "40", -5],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022", ""],
    "Score": [95.5, None, 88.0, 92.5, "", 105], 
    "Status": ["Active", "Inactive", None, "", "Active", "Active"]
}

df_messy = pd.DataFrame(data)

df_messy.replace("", np.nan, inplace=True)

df_messy["Age"] = pd.to_numeric(df_messy["Age"], errors="coerce")
df_messy["Score"] = pd.to_numeric(df_messy["Score"], errors="coerce")
df_messy["Signup Date"] = pd.to_datetime(df_messy["Signup Date"], errors="coerce")


df_messy["Name"].fillna("Unknown", inplace=True)
df_messy["Status"].fillna("Unknown", inplace=True)
df_messy["Age"].fillna(df_messy["Age"].median(), inplace=True)

print("Cleaned Custom Data:\n", df_messy)

Cleaned Custom Data:
       Name   Age Signup Date  Score    Status
0    Alice  25.0  2022-01-01   95.5    Active
1      Bob  30.0         NaT    NaN  Inactive
2  Charlie  35.0         NaT   88.0   Unknown
3    David  30.0         NaT   92.5   Unknown
4  Unknown  40.0         NaT    NaN    Active
5    Frank  -5.0         NaT  105.0    Active

C:\Users\kingj\AppData\Local\Temp\ipykernel_26220\2133098546.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_messy.replace("", np.nan, inplace=True)

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

In [24]:
survey_data = {
    "survey_id": [101, 102, 103, 104, 105],
    "rating": [5, np.nan, 4, 2, None],
    "comments": ["Great!", "", "Okay", None, "Bad"],
    "date": ["2023-01-01", "2023-01-02", "Invalid", "2023-01-04", "2023-01-05"]
}
survey = pd.DataFrame(survey_data)

print("\nNull Report:\n", survey.isnull().sum())

survey["date"] = pd.to_datetime(survey["date"], errors="coerce")
survey.dropna(subset=["date"], inplace=True)
survey["rating"].fillna(survey["rating"].median(), inplace=True)
survey["comments"].fillna("No Comment", inplace=True)

print("\nSurvey Info:")
survey.info()

Null Report:
 survey_id    0
rating       2
comments     1
date         0
dtype: int64

Survey Info:
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   survey_id  4 non-null      int64
 1   rating     4 non-null      float64
 2   comments   4 non-null      object
 3   date       4 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 160.0+ bytes

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |