# 📊 04 - Data Input and Output

Most of data science is about **loading data, exploring it, and saving results**.  
In this notebook you will learn:
- Reading CSV files with Pandas
- Inspecting DataFrames (`head`, `info`, `describe`)
- Writing data back to CSV
- Reading Excel files (if available)

## 1. Reading CSV Files

In [4]:
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
"""
with open("students.csv", "w") as f:
    f.write(data)

# Read CSV into DataFrame
df = pd.read_csv("students.csv")
df

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

✅ **Your Turn**: Create your own small CSV (3–5 rows) and read it into Pandas.

In [5]:
import pandas as pd
data = """
Class,Grade,Letter
Math,30,F
English,20,F
Science,5,F
"""

with open("grades.csv", "w") as f:
    f.write(data)

df = pd.read_csv("grades.csv")
print(df)

     Class  Grade Letter
0     Math     30      F
1  English     20      F
2  Science      5      F

## 2. Exploring DataFrames

In [6]:
# Look at the first rows
df.head()

     Class  Grade Letter
0     Math     30      F
1  English     20      F
2  Science      5      F

In [7]:
# Info about columns and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Class   3 non-null      object
 1   Grade   3 non-null      int64
 2   Letter  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [8]:
# Summary statistics
df.describe()

           Grade
count   3.000000
mean   18.333333
std    12.583057
min     5.000000
25%    12.500000
50%    20.000000
75%    25.000000
max    30.000000

✅ **Your Turn**: Use `.head()` to preview your dataset and `.describe()` to see basic statistics.

In [11]:
import pandas as pd
data = """
Class,Grade,Letter
Math,30,F
English,20,F
Science,5,F
"""

with open("grades.csv", "w") as f:
    f.write(data)

df = pd.read_csv("grades.csv")
print(df.head())
print(df.describe())

     Class  Grade Letter
0     Math     30      F
1  English     20      F
2  Science      5      F
           Grade
count   3.000000
mean   18.333333
std    12.583057
min     5.000000
25%    12.500000
50%    20.000000
75%    25.000000
max    30.000000

## 3. Writing CSV Files

In [9]:
# Save the DataFrame to a new CSV
df.to_csv("students_copy.csv", index=False)
%ls *.csv

 Volume in drive C is Windows SSD
 Volume Serial Number is FA10-B13F

 Directory of c:\Users\kingj\Desktop\DataScience\tracotr-DataScience-2025\Completed\05-Foundations

10/11/2025  10:24 PM                60 grades.csv
10/11/2025  10:24 PM                55 students.csv
10/11/2025  10:24 PM                58 students_copy.csv
               3 File(s)            173 bytes
               0 Dir(s)  117,425,119,232 bytes free

✅ **Your Turn**: Save your DataFrame to a CSV file called `my_data.csv`.

In [13]:
import pandas as pd
data = """
Class,Grade,Letter
Math,30,F
English,20,F
Science,5,F
"""

with open("grades.csv", "w") as f:
    f.write(data)

df = pd.read_csv("grades.csv")
df.to_csv("my_data.csv", index=False)

## 4. Reading Excel Files

In [14]:
# Optional: Requires 'openpyxl' installed
# Save to Excel
df.to_excel("students.xlsx", index=False)

# Read Excel file
pd.read_excel("students.xlsx")

     Class  Grade Letter
0     Math     30      F
1  English     20      F
2  Science      5      F

✅ **Your Turn**: Try saving your dataset to Excel and reading it back (if supported in your environment).

In [15]:
import pandas as pd
data = """
Class,Grade,Letter
Math,30,F
English,20,F
Science,5,F
"""

with open("grades.csv", "w") as f:
    f.write(data)

df = pd.read_csv("grades.csv")
df.to_excel("grades.xlsx", index=False)
pd.read_excel("grades.xlsx")

     Class  Grade Letter
0     Math     30      F
1  English     20      F
2  Science      5      F

---
### Summary
- `pd.read_csv` loads data into a DataFrame.
- Use `.head()`, `.info()`, `.describe()` to explore quickly.
- `df.to_csv` and `df.to_excel` save results.
- Pandas makes file I/O simple and reliable.